services:
    manuel_translation.translations_repository:
        class: ManuelAguirre\Bundle\TranslationBundle\Entity\TranslationRepository
        factory: [@doctrine.orm.entity_manager, getRepository]
        arguments: ['ManuelTranslationBundle:Translation']

    manuel_translation.translations_doctrine_loader:
        class: ManuelAguirre\Bundle\TranslationBundle\Translation\Loader\DoctrineLoader
        arguments: [@manuel_translation.translations_repository, %manuel_translation.filename_template%]
        tags:
            - { name: translation.loader, alias: doctrine }

    manuel_translation.translation_type:
        class: ManuelAguirre\Bundle\TranslationBundle\Form\Type\TranslationType
        arguments: [@manuel_translation.translations_repository]
        tags:
            - { name: form.type , alias: manuel_translation }

    manuel_translation.translation_manager:
        class: ManuelAguirre\Bundle\TranslationBundle\Translation\TranslationManager
        arguments:
            - @translation.extractor
            - @manuel_translation.translation_loader
            - @manuel_translation.translations_doctrine_loader
            - @manuel_translation.translations_doctrine_dumper
            - @manuel_translation.translations_repository
            - %manuel_translation.locales%
            - %manuel_translation.extract_dirs%
            - %manuel_translation.translations_files_dirs%
        calls:
            - ['setBackupDumper', [@translation.dumper.php]]
            - ['setBackupDir', [%manuel_translation.translations_backup_dir%]]
#
#    manuel_translation.twig_text_extension:
#        class: Twig_Extensions_Extension_Text
#        tags:
#            - { name: twig.extension }