services:
    manuel_translation.translations_doctrine_dumper:
        class: ManuelAguirre\Bundle\TranslationBundle\Translation\Dumper\DoctrineDumper
        arguments:
            - @doctrine.orm.entity_manager
            - @manuel_translation.translations_repository
            - %manuel_translation.locales%
        tags:
            - { name: translation.dumper, alias: doctrine }

    manuel_translation.translation_form_filter_type:
        class: ManuelAguirre\Bundle\TranslationBundle\Form\Type\TranslationFilterType
        arguments: [@manuel_translation.translations_repository]
        tags:
            - { name: form.type, alias: translation_filter }

    manuel_translation.translation_loader:
        class: Symfony\Bundle\FrameworkBundle\Translation\TranslationLoader