services:
    manuel_translation.translations_doctrine_dumper:
        class: ManuelAguirre\Bundle\TranslationBundle\Translation\Dumper\DoctrineDumper
        arguments:
            - @doctrine.orm.entity_manager
            - @manuel_translation.translations_repository
            - %manuel_translation.locales%
        tags:
            - { name: translation.dumper, alias: doctrine }

    manuel_translation.translation_form_filter_type:
        class: ManuelAguirre\Bundle\TranslationBundle\Form\Type\TranslationFilterType
        arguments: [@manuel_translation.translations_repository]
        tags:
            - { name: form.type, alias: translation_filter }

    manuel_translation.translation_loader:
        class: Symfony\Bundle\FrameworkBundle\Translation\TranslationLoader

    manuel_translation.debug_translator:
        class: ManuelAguirre\Bundle\TranslationBundle\Translation\DebugTranslator
        arguments: [@manuel_translation.debug_translator.inner]
        decorates: translator

    manuel_translation.translations_data_collector:
        class: ManuelAguirre\Bundle\TranslationBundle\DataCollector\TranslationDataCollector
        arguments:
            - @manuel_translation.debug_translator
            - %manuel_translation.locales%
        tags:
            -
                name: data_collector
                template: @ManuelTranslation/DataCollector/translations.html.twig
                id: manuel_translations

    manuel_translation.doctrine.translation_log_listener:
        class: ManuelAguirre\Bundle\TranslationBundle\Doctrine\Listener\TranslationLogListener
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
